<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_entity_alter().
 */
function gsb_feature_image_cta_fpp_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['gsb_image_cta_fpp'] = array(
    'label' => t('Add GSB Image CTA'),
    'pane category' => t('GSB Category'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_image_cta_fpp.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/gsb-image-cta-fpp',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_form_alter()
 */
function gsb_feature_image_cta_fpp_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form' && $form['#bundle'] == 'gsb_image_cta_fpp') {

      $form['field_editorial_summary']['und'][0]['value']['#states'] = array(
        'visible' => array(
          ':input[name="field_text_position[und]"]' => array(
            array('value' => 'Top'),
          ),
        ),
      );

  }

}