<?php
/**
 * @file
 * Code for the GSB Feature Image CTA FPP feature.
 */

include_once 'gsb_feature_image_cta_fpp.features.inc';

/**
 * Implements hook_entity_alter().
 */
function gsb_feature_image_cta_fpp_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['image_cta'] = array(
    'label' => t('Image CTA'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/image-cta',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_form_alter()
 */
function gsb_feature_image_cta_fpp_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form' && !empty($form['#bundle']) && $form['#bundle'] == 'image_cta') {
    $form['field_image_cta_bg_color']['#prefix'] = 
      '<strong>Check "Stock Content" first to see if the image CTA you need already exists.</strong></br>' .
      '<a href="https://onegsb.stanford.edu/group/gsb-web-authors" target="_blank">View image CTA standards</a> for guidance on using this feature.';  
    $form['reusable']['admin_title']['#field_suffix'] = 
      '<div class="description"><strong>Format</strong>: Feature Name: Subject | <strong>Example</strong>: Image CTA: Directions | Parking</div>';
    if ($form['reusable']['reusable']['#default_value'] != "1") {
      $form['reusable']['warning']['#markup'] = '<div class="description">' . 'Check this box if you want to use this feature on other pages.' . '</div>';
    }
    $form['#after_build'][] = 'gsb_feature_image_cta_fpp_after_build_form_alter';
  }

}

/**
 * After build form handler.
 *
 * We use this to fix up the validation form_error message to use the link's label(title).
 *
 * @see gsb_feature_image_cta_fpp_form_alter()
 */
function gsb_feature_image_cta_fpp_after_build_form_alter($form) {
  if ($form['#form_id'] == 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form' && $form['#bundle'] == 'image_cta') {  
    $form['field_link_single']['und'][0]['url']['#suffix'] = 
      '<div class="description">Do not include "http://gsb.stanford.edu/" for links to pages on this site. <strong>Example</strong>: programs/mba</div>';
    $form['field_link_single']['und'][0]['url']['#title'] = $form['field_link_single']['und']['#title'];
  }
  return $form;
}

/**
 * Implements hook_preprocess_HOOK() for fieldable-panels-pane.tpl.php.
 */
function gsb_feature_image_cta_fpp_preprocess_fieldable_panels_pane(&$variables) {
  if ($variables['elements']['#bundle'] != 'image_cta') {
    return;
  }
  // Add classes based on the position and color chosen.
  try {
    $wrapper = entity_metadata_wrapper('fieldable_panels_pane', $variables['elements']['#element']);
    $variables['classes_array'][] = 'image-cta-color-' . $wrapper->field_image_cta_bg_color->value();
  }
  catch (EntityMetadataWrapperException $e) {
    // If the fields are ever missing/renamed, Entity API will throw an
    // exception instead of using watchdog.
    watchdog('gsb_feature_image_cta_fpp', 'In @function on line @line: "@message"', array('@function' => __FUNCTION__, '@line' => __LINE__, '@message' => $e->getMessage()), WATCHDOG_ERROR);
  }
  $url = $variables['content']['field_link_single'][0]['#element']['url'];
  $variables['content']['field_link_single'][0]['#element']['url'] = utf8_decode(urldecode($url));
}
